//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18052
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 之類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWeb() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResWeb", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 企業介紹 的當地語系化字串。
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購物 的當地語系化字串。
        /// </summary>
        internal static string btn_Shopping {
            get {
                return ResourceManager.GetString("btn_Shopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我要結帳 的當地語系化字串。
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡我們 的當地語系化字串。
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NT$ 的當地語系化字串。
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證碼不正確 的當地語系化字串。
        /// </summary>
        internal static string Error_Valide {
            get {
                return ResourceManager.GetString("Error_Valide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連接伺服器發生錯誤，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Err_ConnectionServerOut {
            get {
                return ResourceManager.GetString("Err_ConnectionServerOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已處於登錄狀態無法完成 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginState {
            get {
                return ResourceManager.GetString("Err_LoginState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失敗，請重新輸Email及密碼。 的當地語系化字串。
        /// </summary>
        internal static string Err_LoginUnCorrect {
            get {
                return ResourceManager.GetString("Err_LoginUnCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先登錄以完成該項作業 的當地語系化字串。
        /// </summary>
        internal static string Err_LogoutState {
            get {
                return ResourceManager.GetString("Err_LogoutState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件已存在，請勿重複註冊。 的當地語系化字串。
        /// </summary>
        internal static string Err_MailHasExist {
            get {
                return ResourceManager.GetString("Err_MailHasExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 郵件帳號不存在 的當地語系化字串。
        /// </summary>
        internal static string Err_MailNotExist {
            get {
                return ResourceManager.GetString("Err_MailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼確認不符 的當地語系化字串。
        /// </summary>
        internal static string Err_npwdNotEqualspwd {
            get {
                return ResourceManager.GetString("Err_npwdNotEqualspwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼不可等於舊密碼 的當地語系化字串。
        /// </summary>
        internal static string Err_opwdEqualnpwd {
            get {
                return ResourceManager.GetString("Err_opwdEqualnpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該筆訂單已支付過 的當地語系化字串。
        /// </summary>
        internal static string Err_PayHasFinished {
            get {
                return ResourceManager.GetString("Err_PayHasFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 各密碼欄位不可以有空白 的當地語系化字串。
        /// </summary>
        internal static string Err_pwdHasBlank {
            get {
                return ResourceManager.GetString("Err_pwdHasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統發生Session遺失，請聯絡管理員。 的當地語系化字串。
        /// </summary>
        internal static string Err_SessionLost {
            get {
                return ResourceManager.GetString("Err_SessionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤 的當地語系化字串。
        /// </summary>
        internal static string Err_System {
            get {
                return ResourceManager.GetString("Err_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回首頁 的當地語系化字串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登錄 的當地語系化字串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 台鑫&lt;info@jcin.com.tw&gt; 的當地語系化字串。
        /// </summary>
        internal static string MailAdmin {
            get {
                return ResourceManager.GetString("MailAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 感謝您加入會員 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectAddMember {
            get {
                return ResourceManager.GetString("MailSubjectAddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 富堤納購物網【訂單資訊】 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectOrderInfo {
            get {
                return ResourceManager.GetString("MailSubjectOrderInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼重設通知 的當地語系化字串。
        /// </summary>
        internal static string MailSubjectRestPWD {
            get {
                return ResourceManager.GetString("MailSubjectRestPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最新消息 的當地語系化字串。
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您購買了 的當地語系化字串。
        /// </summary>
        internal static string Note1 {
            get {
                return ResourceManager.GetString("Note1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 營養顧問: 的當地語系化字串。
        /// </summary>
        internal static string Note2 {
            get {
                return ResourceManager.GetString("Note2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購物車 的當地語系化字串。
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品介紹 的當地語系化字串。
        /// </summary>
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 http://www.tstw.com.tw 的當地語系化字串。
        /// </summary>
        internal static string PublicUrl {
            get {
                return ResourceManager.GetString("PublicUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 問與答 的當地語系化字串。
        /// </summary>
        internal static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數量 的當地語系化字串。
        /// </summary>
        internal static string Tag_Amount {
            get {
                return ResourceManager.GetString("Tag_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我要結帳 的當地語系化字串。
        /// </summary>
        internal static string Tag_Check {
            get {
                return ResourceManager.GetString("Tag_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認寄件資料 的當地語系化字串。
        /// </summary>
        internal static string Tag_ConfirmMailData {
            get {
                return ResourceManager.GetString("Tag_ConfirmMailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認訂單 的當地語系化字串。
        /// </summary>
        internal static string Tag_ConfirmOrder {
            get {
                return ResourceManager.GetString("Tag_ConfirmOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Tag_Delete {
            get {
                return ResourceManager.GetString("Tag_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子郵件 的當地語系化字串。
        /// </summary>
        internal static string Tag_Email {
            get {
                return ResourceManager.GetString("Tag_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購物完成後，您將自動升級成為會員。 的當地語系化字串。
        /// </summary>
        internal static string Tag_FinishToMember {
            get {
                return ResourceManager.GetString("Tag_FinishToMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第一次購物請按此 的當地語系化字串。
        /// </summary>
        internal static string Tag_FirstHere {
            get {
                return ResourceManager.GetString("Tag_FirstHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘記密碼 的當地語系化字串。
        /// </summary>
        internal static string Tag_ForgetPWD {
            get {
                return ResourceManager.GetString("Tag_ForgetPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 項目 的當地語系化字串。
        /// </summary>
        internal static string Tag_Item {
            get {
                return ResourceManager.GetString("Tag_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登錄 的當地語系化字串。
        /// </summary>
        internal static string Tag_Login {
            get {
                return ResourceManager.GetString("Tag_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 會員登錄 的當地語系化字串。
        /// </summary>
        internal static string Tag_MemberLogin {
            get {
                return ResourceManager.GetString("Tag_MemberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        internal static string Tag_Password {
            get {
                return ResourceManager.GetString("Tag_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 運費 的當地語系化字串。
        /// </summary>
        internal static string Tag_ShippFee {
            get {
                return ResourceManager.GetString("Tag_ShippFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購物車 的當地語系化字串。
        /// </summary>
        internal static string Tag_ShoppingCar {
            get {
                return ResourceManager.GetString("Tag_ShoppingCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂單完成 的當地語系化字串。
        /// </summary>
        internal static string Tag_ShoppingCarFinish {
            get {
                return ResourceManager.GetString("Tag_ShoppingCarFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 小計 的當地語系化字串。
        /// </summary>
        internal static string Tag_SubCount {
            get {
                return ResourceManager.GetString("Tag_SubCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 金額小計 的當地語系化字串。
        /// </summary>
        internal static string Tag_SubTotal {
            get {
                return ResourceManager.GetString("Tag_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 總金額 的當地語系化字串。
        /// </summary>
        internal static string Tag_Total {
            get {
                return ResourceManager.GetString("Tag_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單價 的當地語系化字串。
        /// </summary>
        internal static string Tag_UnitPrice {
            get {
                return ResourceManager.GetString("Tag_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 禾吉辰 的當地語系化字串。
        /// </summary>
        internal static string WebTitle {
            get {
                return ResourceManager.GetString("WebTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 微博 的當地語系化字串。
        /// </summary>
        internal static string Weibo {
            get {
                return ResourceManager.GetString("Weibo", resourceCulture);
            }
        }
    }
}
